### ISSUE TITLE
GitHub authentication instead of manual Access Token

### ISSUE THREAD

**Issue by AlexWayfer** [jakedeichert/github-release-checker#1]
Hello!

I'd be handy with [GitHub authentication](https://developer.github.com/v3/guides/basics-of-authentication/) instead of direct input for Access Token.

Thanks.

**Comment by jakedeichert** [comment]
Hey! Thanks for creating the first issue!

I agree it would be easier first-time setup for github auth to be supported. 

Is there any other reason than it just being a little easier to use?

**Comment by AlexWayfer** [comment]
> Is there any other reason than it just being a little easier to use?

Security? Direct Access Token for copy-pasting is less secure than OAuth, I think.

**Comment by jakedeichert** [comment]
I just took a quick look at their OAuth process. It looks like they generate an access token and give it back to the app which saves you from manually having to generate an access token. 

So in both situations, I would still store your access token in localstorage/indexedDB. The only real security difference would be that you don't have to copy/paste a token manually. I'm trying to think how this could be insecure... other than some form of malware that collects all clipboard content 😅

I still agree though, using the OAuth flow is easier. I think it would also prevent a user from accidentally giving more privileges than what is required, which is just public access.

**Comment by AlexWayfer** [comment]
> I'm trying to think how this could be insecure... other than some form of malware that collects all clipboard content sweat_smile

It's like… human factor, you know. You (and your app) don't control this stage, and you can't be sure that user don't send this key somewhere.

I know, it's not this app scope, but… more security is better, I guess.

> I think it would also prevent a user from accidentally giving more privileges than what is required, which is just public access.

Yes!

**Comment by jakedeichert** [comment]
I checked out the github authentication docs further.

https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

It looks like I'd need to register this app with github and also run a backend server in order to work with their OAuth system.

It currently doesn't look possible for a client-side-only app to authenticate via github OAuth without exposing a secret key they assign to my app. 

Am I missing something else that you are aware of perhaps?

At this point, if I have to run my own auth server or lambda, that might be out of scope for this project 😅

**Comment by jakedeichert** [comment]
I'll close this for now then.

I might come back to this in the future... might be a good thing to try out still!
